protected/modules/admin/controllers/BookController.php
<?php

class BookController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/lay/book_layout';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','manage','admin','del'), //create and update only use in developing mode, it will be remove when it finish
				'users'=>array('*'),
			),
			/*array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),*/
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Book;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Book']))
		{
			$rnd = rand(0,9999);
			$model->attributes=$_POST['Book'];
			$uploadedFile=CUploadedFile::getInstance($model,'image');
            $fileName = "{$rnd}-{$uploadedFile}";  // random number + file name
            $model->image = $fileName;
			if($model->save()){
				$uploadedFile->saveAs(Yii::app()->basePath.'/../images/'.$fileName); 
				Yii::app()->user->setFlash('message','File Berhasil Di Simpan!!!' );
				//$this->redirect(array('view','id'=>$model->book_id));
			}
				
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
		{
			$model=$this->loadModel($id);
	 
			if(isset($_POST['Book']))
			{
				$_POST['Banner']['image'] = $model->image;
				$model->attributes=$_POST['Book'];
	 
				$uploadedFile=CUploadedFile::getInstance($model,'image');
	 
				if($model->save())
				{
					if(!empty($uploadedFile))  // check if uploaded file is set or not
					{
						$uploadedFile->saveAs(Yii::app()->basePath.'/../images/'.$model->image);
					}
					Yii::app()->user->setFlash('message','File Berhasil Di Simpan!!!' );
                                        //$this->redirect(array('view','id'=>$model->book_id));
				}
	 
			}
	 
			$this->render('update',array(
				'model'=>$model,
			));
		}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();
		$this->redirect(array('manage'));
		
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		//if(!isset($_GET['ajax']))
			//$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Book');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Book('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Book']))
			$model->attributes=$_GET['Book'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Book the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Book::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Book $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='book-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	/**
	* Display all books and option(update / delete)
	*/
	public function actionManage(){
		$models = Book::model()->findAll();
		
		$this->render('manage',array('models'=>$models));
	}
	
	/**
	* Delete specific model
	*/
	public function actionDel($id){
		$this->loadModel($id)->delete();
		
		$this->redirect(array('manage'));
	}
}

protected/modules/admin/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		$this->layout = '//layout/column2';
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()){
				if (Yii::app()->user->role == 2)
					$this->redirect(Yii::app()->createUrl('site/admin'));
				else
					$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
     
	/**
	* Register new user
	*/
	public function actionRegister(){
		$this->layout = '//layout/mainReg';
		
		$userModel = new User;
		$customerModel = new Customer;
		
		if(isset($_POST['User'],$_POST['Customer'])){
			$userModel->attributes = $_POST['User'];
			$customerModel->attributes = $_POST['Customer'];
			
			if(User::model()->findByAttribute(array('username'=>$userModel->username)) !== NULL){
				$userModel->save();
			}
		}
		
		$this->render('register',array('userModel'=>$userModel,'customerModel'=>$customerModel));
	}
	
	/**
	* How To order
	*/
	public function actionHowToOrder(){
		$this-> layout = '/layout/column2';
		
		$this->render('howToOrder');
	}
	
	/**
	* About Us
	*/
	public function actionAboutUs(){
		$this-> layout = '/layout/column2';
		
		$this->render('aboutUs');
	}
	
	/**
	* faq
	*/
	public function actionFaq(){
		$this-> layout = '/layout/column2';
		
		$this->render('faq');
	}
}

protected/modules/admin/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/lay/book_layout';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','update','del','delete','manage'),
				'users'=>array('*'),
			),
			/*array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),*/
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->password = $model->hashPassword($model->password);
			$available = User::model()->findByAttributes(array('username'=>$model->username));
			if($available !== NULL){
				Yii::app()->user->setFlash('error',"Username already exist!!!");
			} else {
				if($model->save())
					$this->redirect(array('view','id'=>$model->user_id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->password = $model->hashPassword($model->password);
			if($model->save())
				$this->redirect(array('view','id'=>$model->user_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function actionManage(){
		$models = User::model()->findAll();
		$this->render('manage',array('models'=>$models));
	}
	public function actionDel($id){
		$this->loadModel($id)->delete();
		$this->redirect (array('manage'));
	}
}

protected/modules/admin/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/modules/admin/views/layouts/column2.php
<?php /* @var $this Controller */ ?>

<?php $this->beginContent('//layouts/mainAdmin'); ?>
	
				<div class="col-md-3 column" style="margin-top:50px">
					<div class="panel-group" id="panel-794225" style="margin-bottom: 5px">
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-905286"><i class="fa fa-book" style="margin-right:15px;"></i>Book</a>
							</div>
							<div id="panel-element-905286" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('book/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('book/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-298581"><i class="fa fa-database fa-lg" style="margin-right:12px;"></i>Book Owner</a>
							</div>
							<div id="panel-element-298581" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('owner/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('owner/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-797816"><i class="fa fa-user-plus fa-lg" style="margin-right:7px;"></i>User</a>
							</div>
							<div id="panel-element-797816" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('user/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-905284"><i class="fa fa-book" style="margin-right:15px;"></i>Paket</a>
							</div>
							<div id="panel-element-905284" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('paket/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('paket/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-905285"><i class="fa fa-book" style="margin-right:15px;"></i>Transaksi</a>
							</div>
							<div id="panel-element-905285" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('transaction/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('transaction/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="col-md-9 column" style="margin-left:70px">
					<?php echo $content;?>
				</div>
			</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-9">
		<?php echo $content; ?>
	</div>
<?php $this->endContent(); ?>

protected/modules/admin/views/layouts/main.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>ReadingWalk</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
	
		<link href="<?php echo Yii::app()->request->baseUrl;?>/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?php echo Yii::app()->request->baseUrl;?>/css/admin.css" rel="stylesheet">
		<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl;?>/css/font-awesome.min.css">

		<!-- Fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
		<link rel="shortcut icon" href="img/favicon.png">
  
	</head>

	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class = "container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="<?php echo Yii::app()->homeUrl;?>">ReadingWalk</a>
				</div>
			
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="<?php echo Yii::app()->createUrl('site/logout');?>" style="padding-right:15px; padding-bottom: 10px">Logout</a>
						</li>
						<li>
							<a href="#" style="padding-right:40px; padding-bottom: 10px"><?php echo Yii::app()->user->name;?></a>
						</li>
					</ul>
				</div>	
				
			</div>
		</nav>
		
		<div class="container">
			
			
			<?php echo $content; ?>
                   
		</div>
	
		<div class="footer">
                    <div class="container">
			<div class="row">
				<center>
					<a href="<?php echo Yii::app()->homeUrl;?>">Home</a>&nbsp;|&nbsp;
					<a href="<?php echo Yii::app()->createUrl('site/aboutUs');?>">About Us</a>&nbsp;|&nbsp;
					<a href="<?php echo Yii::app()->createUrl('site/howToOrder');?>">How to Order</a>&nbsp;|&nbsp;
					<a href="<?php echo Yii::app()->createUrl('site/faq');?>">FAQ</a>
				</center>	
			</div>
                    
			<div class = "row">
				<center>© Copyright 2015 - 2020 Reading Walk. All Rights Reserved</center>
			</div>
                    </div>
		</div>
		
		<script src="<?php echo Yii::app()->request->baseUrl;?>/css/js/jquery.min.js"></script>
		<script src="<?php echo Yii::app()->request->baseUrl;?>/css/js/bootstrap.min.js"></script>
		<script src="<?php echo Yii::app()->request->baseUrl;?>/css/js/scripts.js"></script>
		<script src="<?php echo Yii::app()->request->baseUrl;?>/css/js/readingwalk.js"></script>
	</body>
</html>