protected/modules/admin/controllers/BookController.php
<?php

class BookController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/lay/book_layout';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','manage','admin','del'), //create and update only use in developing mode, it will be remove when it finish
				'users'=>array('*'),
			),
			/*array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),*/
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Book;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Book']))
		{
			$rnd = rand(0,9999);
			$model->attributes=$_POST['Book'];
			$uploadedFile=CUploadedFile::getInstance($model,'image');
            $fileName = "{$rnd}-{$uploadedFile}";  // random number + file name
            $model->image = $fileName;
			if($model->save()){
				$uploadedFile->saveAs(Yii::app()->basePath.'/../images/'.$fileName); 
				Yii::app()->user->setFlash('message','File Berhasil Di Simpan!!!' );
				//$this->redirect(array('view','id'=>$model->book_id));
			}
				
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
		{
			$model=$this->loadModel($id);
	 
			if(isset($_POST['Book']))
			{
				$_POST['Banner']['image'] = $model->image;
				$model->attributes=$_POST['Book'];
	 
				$uploadedFile=CUploadedFile::getInstance($model,'image');
	 
				if($model->save())
				{
					if(!empty($uploadedFile))  // check if uploaded file is set or not
					{
						$uploadedFile->saveAs(Yii::app()->basePath.'/../images/'.$model->image);
					}
					Yii::app()->user->setFlash('message','File Berhasil Di Simpan!!!' );
                                        //$this->redirect(array('view','id'=>$model->book_id));
				}
	 
			}
	 
			$this->render('update',array(
				'model'=>$model,
			));
		}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();
		$this->redirect(array('manage'));
		
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		//if(!isset($_GET['ajax']))
			//$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Book');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Book('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Book']))
			$model->attributes=$_GET['Book'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Book the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Book::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Book $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='book-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	/**
	* Display all books and option(update / delete)
	*/
	public function actionManage(){
		$models = Book::model()->findAll();
		
		$this->render('manage',array('models'=>$models));
	}
	
	/**
	* Delete specific model
	*/
	public function actionDel($id){
		$this->loadModel($id)->delete();
		
		$this->redirect(array('manage'));
	}
}

protected/modules/admin/controllers/OwnerController.php
<?php

class OwnerController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/lay/book_layout';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','manage','del'),
				'users'=>array('*'),
			),
			/*array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),*/
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Owner;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Owner']))
		{
			$model->attributes=$_POST['Owner'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->owner_id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Owner']))
		{
			$model->attributes=$_POST['Owner'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->owner_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Owner');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Owner('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Owner']))
			$model->attributes=$_GET['Owner'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Owner the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Owner::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Owner $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='owner-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function actionManage(){
		$models = Owner::model()->findAll();
		$this->render('manage',array('models'=>$models));
	}
	public function actionDel($id){
		$this->loadModel($id)->delete();
		$this->redirect(array('manage'));
	}
	
}

protected/modules/admin/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/lay/book_layout';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','update','del','delete','manage'),
				'users'=>array('*'),
			),
			/*array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),*/
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->password = $model->hashPassword($model->password);
			$available = User::model()->findByAttributes(array('username'=>$model->username));
			if($available !== NULL){
				Yii::app()->user->setFlash('error',"Username already exist!!!");
			} else {
				if($model->save())
					$this->redirect(array('view','id'=>$model->user_id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->password = $model->hashPassword($model->password);
			if($model->save())
				$this->redirect(array('view','id'=>$model->user_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function actionManage(){
		$models = User::model()->findAll();
		$this->render('manage',array('models'=>$models));
	}
	public function actionDel($id){
		$this->loadModel($id)->delete();
		$this->redirect (array('manage'));
	}
}

protected/modules/admin/views/layouts/lay/book_layout.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ReadingWalk</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

	<!--link rel="stylesheet/less" href="less/bootstrap.less" type="text/css" /-->
	<!--link rel="stylesheet/less" href="less/responsive.less" type="text/css" /-->
	<!--script src="js/less-1.3.3.min.js"></script-->
	<!--append ‘#!watch’ to the browser URL, then refresh the page. -->
	
	<link href="<?php echo Yii::app()->request->baseUrl;?>/assets/theme/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?php echo Yii::app()->request->baseUrl;?>/assets/theme/css/style.css" rel="stylesheet">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
  <![endif]-->

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="img/favicon.png">
  
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl;?>/assets/theme/css/js/jquery.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl;?>/assets/theme/css/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl;?>/assets/theme/css/js/scripts.js"></script>
</head>
<body>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">ReadingWalk</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li>
							<i class="fa fa-cart-plus fa-2x" style="padding-right: 50px; color: white; padding-left: 10px; padding-bottom: 10px"></i>
						</li>
						<li>
							<a href="#" style="padding-right:15px; padding-bottom: 10px">Register</a>
						</li>
						<li>
							<a href="#" style="padding-right:40px; padding-bottom: 10px">LogIn</a>
						</li>
					</ul>
				</div>
				
</nav>
<br><br><br>
<div class="container">
<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="row clearfix">
				<div class="col-md-2 column" style="margin-top:50px">
					<div class="panel-group" id="panel-794225" style="margin-bottom: 5px">
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-905286"><i class="fa fa-book" style="margin-right:15px;"></i>Book</a>
							</div>
							<div id="panel-element-905286" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('book/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('book/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-298581"><i class="fa fa-database fa-lg" style="margin-right:12px;"></i>Book Owner</a>
							</div>
							<div id="panel-element-298581" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('owner/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('owner/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-797816"><i class="fa fa-user-plus fa-lg" style="margin-right:7px;"></i>User</a>
							</div>
							<div id="panel-element-797816" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('user/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-905284"><i class="fa fa-book" style="margin-right:15px;"></i>Paket</a>
							</div>
							<div id="panel-element-905284" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('paket/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('paket/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-794225" href="#panel-element-905285"><i class="fa fa-book" style="margin-right:15px;"></i>Transaksi</a>
							</div>
							<div id="panel-element-905285" class="panel-collapse collapse">
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('transaction/create');?>">Add</a></li>
								</div>
								<div class="panel-body">
									<li><a href="<?php echo $this-> createUrl ('transaction/manage');?>">Manage</a></li>
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<div class="col-md-6 column" style="margin-left:70px">
					<?php echo $content;?>
				</div>
			</div>
			</div>
		</div>
	</div>

<br><br>	
<div class="row clearfix">
		<div class="col-md-12 column" style="background-color:black; opacity:0.9">
			<div class="col-md-4 col-sm-4">
				<center>
					<a href="">Home</a>&nbsp;|&nbsp;
					<a href="http://readingwalk.com/index.php/site/aboutus">About Us</a>&nbsp;|&nbsp;
					<a href="http://readingwalk.com/index.php/site/howtoorder">How to Order</a>&nbsp;|&nbsp;
					<a href="http://readingwalk.com/index.php/site/faq">FAQ</a>
				</center>
			</div>
			<div class="col-md-4 col-sm-4 no-padding">
				<center>© Copyright 2015 - 2020 Ked. All Rights Reserved</center>
			</div>
			<div class="col-md-4 col-sm-4">
				<center>
					<a href="https://www.facebook.com/" target="_blank"><span class="social-box-o"><i class="fa fa-facebook"></i></span> facebook</a>&nbsp;&nbsp;
					<a href="https://twitter.com/" target="_blank"><span class="social-box-o"><i class="fa fa-twitter"></i></span> twitter</a>&nbsp;&nbsp;
					<a href="http://readingwalk.com/#"><span class="social-box-o"><i class="fa fa-google-plus"></i></span> google+</a>
				</center>
			</div>
		</div>
</div>
</body>
</html>
